### ISSUE TITLE
npm start가 동작하질 않습니다.

### ISSUE THREAD

**Issue by chul-hyun** [fmaru/fmaru#1]
readme.md 파일에 적혀진 설명서대로 하려니.. npm start --save-dev가 동작하질 않네요.

**Comment by chul-hyun** [comment]
혹시 npm install --save-dev 아닌가요?

**Comment by fmaru** [comment]
맞습니다. 잘못 써놨었네요. 제보 감사합니다. 수정해두겠습니다.
